{% set name = "aiosmtplib" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e03a96fa4692c8550cca4957834bb3e49651aba3ce34f161c03c8c0922beef6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - poetry
  run:
    - python

test:
  imports:
    - aiosmtplib

about:
  home: https://github.com/cole/aiosmtplib
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Asynchronous SMTP client for use with asyncio.
  doc_url: https://aiosmtplib.readthedocs.io/
  dev_url: https://github.com/cole/aiosmtplib

extra:
  recipe-maintainers:
    - mcs07
