{% set name = "aiosmtplib" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9629a0d8786ab1e5f790ebbbf5cbe7886fedf949a3f52fd7b27a0360f6233422

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - aiosmtplib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cole/aiosmtplib
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Asynchronous SMTP client for use with asyncio.
  doc_url: https://aiosmtplib.readthedocs.io/
  dev_url: https://github.com/cole/aiosmtplib

extra:
  recipe-maintainers:
    - thewchan
