{% set name = "aiosmtplib" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43580604b152152a221598be3037f0ae6359c2817187ac4433bd857bc3fc6513

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.8,<4.0

test:
  imports:
    - aiosmtplib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cole/aiosmtplib
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Asynchronous SMTP client for use with asyncio.
  doc_url: https://aiosmtplib.readthedocs.io/
  dev_url: https://github.com/cole/aiosmtplib

extra:
  recipe-maintainers:
    - thewchan
