{% set name = "aiosmtplib" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 10d426afe923edeb28ce0f007da0ee4060e9e12dd3890c162b22e1958da35761

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - aiosmtplib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cole/aiosmtplib
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Asynchronous SMTP client for use with asyncio.
  doc_url: https://aiosmtplib.readthedocs.io/
  dev_url: https://github.com/cole/aiosmtplib

extra:
  recipe-maintainers:
    - thewchan
