schema_version: 1

context:
  name: aiosmtplib
  version: "5.1.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ac2b418d3260ba62d9cfd0fe7359726e9dc009a4e8e8d9909fdfae332f522a7c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - aiosmtplib
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Asynchronous SMTP client for use with asyncio.
  homepage: https://github.com/cole/aiosmtplib
  repository: https://github.com/cole/aiosmtplib
  documentation: https://aiosmtplib.readthedocs.io/

extra:
  recipe-maintainers:
    - thewchan
