schema_version: 1

context:
  name: aiosmtplib
  version: 4.0.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: f0b4933e7270a8be2b588761e5b12b7334c11890ee91987c2fb057e72f566da6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - aiosmtplib
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Asynchronous SMTP client for use with asyncio.
  homepage: https://github.com/cole/aiosmtplib
  repository: https://github.com/cole/aiosmtplib
  documentation: https://aiosmtplib.readthedocs.io/

extra:
  recipe-maintainers:
    - thewchan
